codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 0.80
        threshold: 0.00
        informational: false
    patch:
      default:
        target: 0.80
        threshold: 0.00
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
